### ISSUE TITLE
Support Empty directories

### ISSUE THREAD

**Issue by zhfish** [bozaro/git-as-svn#126]
`Command execution error: svn: E200015: Empty directories is not supported: /Page/a0`

i think it can create `.keep` in Empty directories

**Comment by slonopotamus** [comment]
User can create `.keep` file in empty directories as well.

**Comment by bozaro** [comment]
The main reason that stub files are not created automatically: the user should checkout the same working copy content, regardless of the version control system used.

**Comment by zhfish** [comment]
i can't create manual, i use axure team, it usually create empty directory..

**Comment by zhfish** [comment]
could you add a config ?
auto add a `.keep` when commit a empty directory

**Comment by fcharlie** [comment]
@zhfish when git-as-svn auto create `.keep`，Your working directory will **not have `.keep`** (not run svn checkout ... or other)，but remote has `.keep`，
This situation will continue to occur. The data has been inconsistent. The same `svn rev` is a different directory tree, and you can run an `svn update` that may have an abnormal result.

In remote, git-as-svn convert svn commit create a git commit, so **Empty directory is not supported !**，why not use git ?

**Comment by slonopotamus** [comment]
@fcharlie: that might not be a problem (git-as-svn already has a couple of places where user edits have more consequences than user thinks), though a careful testing is required.

For example, if git-as-svn user adds *.txt eol=native to .gitattributes, automagically all files in repo will pretend as if they were added an svn:eol-style property *in the same commit*.

I see how adding .keep files can be useful - without that you cannot create dirs via repo browser in TortoiseSVN because it doesn't support multiple files edit in a single transaction.

**Comment by bwegh** [comment]
see #339 for what worked for me. It is just a fast fix so I can use git-as-svn at work

**Comment by slonopotamus** [comment]
So. #340 has code that implicitly creates keep files when user commits empty dir via SVN. But it just not going to work due to reasons described in https://github.com/bozaro/git-as-svn/pull/340#issuecomment-609044368

**Comment by slonopotamus** [comment]
As you may have noticed, I've merged #360 that adds limited empty dirs support along with [documentation](https://bozaro.github.io/git-as-svn/htmlsingle/git-as-svn.html#_emptydirs). For the reasons described there and in https://github.com/bozaro/git-as-svn/pull/340#issuecomment-609044368, I do not consider this feature safe to use and it will be disabled by default in git-as-svn.
