### ISSUE TITLE
svn:auto-props should be set automatically by the default .gitattributes

### ISSUE THREAD

**Issue by zeripath** [bozaro/git-as-svn#204]
It's quite awkward adding new files to a git-as-svn repository the svn:eol-style has to match the implied default .gitattributes. It would be good if the svn:auto-props property could be set on checkout to match this implied .gitattributes. (I'm not sure at present if this happens if there is an explicit .gitattributes - but it would good if this too happened.)

**Comment by slonopotamus** [comment]
1. What does your .gitattributes look like?
2. Did you do this? https://bozaro.github.io/git-as-svn/html/en_US/ch02.html#d5e200

The problem with .gitattributes is that by default both git and svn use heuristics and these heuristics are *different*. So the only reliable way is to explicitly tell them what files are binary and what files are text. To add pain of top of this, svn only applies heuristic on initial file add while git does it every time you modify a file.

**Comment by zeripath** [comment]
Heya!

So I don't have a .gitattributes file. Would it not be possible to set it so that the svn:auto-props /inheritable auto-props are based on the defaults that are presumed in the code (GitAttributesFactory)?

**Comment by slonopotamus** [comment]
Okay, I understood what you're talking about. Seems like rootDefaults doesn't work as good at it is supposed to.

**Comment by zeripath** [comment]
Hmm... OK perhaps we should put advice to change the subversion config to switch on local auto-props with appropriate defaults - perhaps suggest a few.

**Comment by zeripath** [comment]
One thing I have noticed is that the GitHub SVN interface doesn't seem to have this eol issue. I don't know enough about SVN properties, are they just ignoring the issue or doing something else?

**Comment by slonopotamus** [comment]
I think they just ignore SVN props.

**Comment by slonopotamus** [comment]
Because we want consistent files content in repo no matter what OS or git/svn user uses. It means that text files have to be with LF in repo and native eols in working copy. If that isn't done, chaos arises. I've seenfiles that had LF and CRLF at the same time. And that confuses both people and tools.

So, we think that marking code files as text and giving them svn:eol-style=native is a Good Thing that prevents platform-dependent inconsistencies. AFAIK, we can also force LF, this is useful for shell scripts that are intended to be used in Cygwin.

Overall, I do not see any problem setting up proper .gitattributes. It doesn't take much time but makes intents explicit and clear. I actually think it a git's mistake that by default it messes with files content. Just say `* -text` in  .gitattributes and neither git nor svn will touch your files and commit them as-is.

**Comment by slonopotamus** [comment]
Hmm... I re-read this issue today and don't understand why it is still open.
