### ISSUE TITLE
Can't connect via IndraWorks SVN Client

### ISSUE THREAD

**Issue by mm060488** [bozaro/git-as-svn#328]
Hello,
at first I want to thank you for this nice project!

I have an issue trying to connect by IndraWorks SVN Client. It is based on SharpSVN 1.8.8.
When I try to connect Authentication seems to fail (Username or Passowrd is wrong).
According to log files  connection is closed immediately:

2020-02-19T10:21:49,479  INFO [SvnServer-thread-5] (SvnServer.java:299) - Client: SVN/1.8.8-SharpSvn-1.8.8-WIN32 (x86-microsoft-windows)
2020-02-19T10:21:49,513  INFO [SvnServer-thread-5] (SvnServer.java:204) - Connection from /x.x.x.x:49997 closed
2020-02-19T10:21:49,515  INFO [SvnServer-thread-5] (SvnServer.java:193) - New connection from: /x.x.x.x:49998
2020-02-19T10:21:49,515  INFO [SvnServer-thread-5] (SvnServer.java:204) - Connection from /x.x.x.x:49998 closed

Can you please help resolving this issue?

Thank you!

**Comment by slonopotamus** [comment]
1. Does it work for you using other SVN clients?
2. What type of `userDB` is configured in git-as-svn?

**Comment by mm060488** [comment]
1. TortoiseSVN works perfectly
2. userDB: !gitlabUsers {}

In Gitlab I use ldap authentication.

**Comment by slonopotamus** [comment]
I suspect that SharpSVN doesn't have SASL authentication support.

**Comment by mm060488** [comment]
So do you think I should try some userDB LDAP configuration instead of gitlabUsers?
Or will there be no difference using this?

**Comment by slonopotamus** [comment]
The only thing that works without SASL is `userDB: !localUsers`. This is equivalent to using `password-db` in `svnserve.conf` if you used native Subversion `svnserve` instead of git-as-svn. In such setup, client uses CRAM-MD5 authentication that it has built-in. The only other built-in method is ANONYMOUS (i.e. no authentication at all). CRAM-MD5 authentication procedure is described a bit [here](http://svnbook.red-bean.com/en/1.7/svn.serverconfig.svnserve.html#svn.serverconfig.svnserve.auth).

In order for CRAM-MD5 to work, SVN server needs to know plain-text password so it can compute a hash that is compared with what client has sent. In all other setups except `userDB: !localUsers`, git-as-svn does _not_ know user password (neither GitLab nor LDAP would give it), so git-as-svn cannot do CRAM-MD5. Instead, in these setups, client sends their credentials to git-as-svn, and git-as-svn then forwards them to authentication service (GitLab OAuth in your case).

**All other authentication mechanisms in SVN are implemented using SASL.**

In your case, you additionally have GitLab integration set up. git-as-svn will not be able to properly talk to GitLab about user that is not authenticated against GitLab, so you *do* want to keep `userDB: !gitlabUsers`.

I'm currently trying to figure out how to test SharpSVN locally, however chances are low. All state of its website strongly hints that this software is abandoned for several years already.

**Comment by mm060488** [comment]
You could download the free trial version of Bosch Rexroth IndraWorks (IndraWorks ML 14V22 P4)

https://www.boschrexroth.com/en/xc/products/product-groups/electric-drives-and-controls/engineering/software-tools/indraworks-engineering

There you can test the VCS-Addon (Teamserver / Teamproject) function

**Comment by slonopotamus** [comment]
Hmm. I've just tested AnkhSVN 2.6.12735.14 (plugin for Visual Studio based on SharpSVN) and it does happily connect to git-as-svn set up with `userDB: !gitlabUsers {}`.

**Comment by slonopotamus** [comment]
@mm060488 could you quickly drop-in SharpSvn dlls from AnkhSVN into that IndraWorks thing and see if that helps? Downloading 6GBs isn't fun.

**Comment by mm060488** [comment]
I will give it a try. Thank you for your support

**Comment by slonopotamus** [comment]
Nice, I don't need to download 6GB :D

WRT empty directories: #126.

**Comment by mm060488** [comment]
The problem is the empty directory seems to be created by the program itself. I just wanted to commit the whole project....

You are able to commit files with the AnkhSVN?

**Comment by slonopotamus** [comment]
So.

Connect problem is kinda "solved". It is caused by SharpSvn libs built in some weird way in IndraWorks. The proper fix would be to contact IndraWorks support and complain that you cannot connect to SASL-enabled SVN server. Preferrably, same scenario should be reproduced against native `svnserve` instead of git-as-svn.

Commiting of empty directories is a different story. It is SVN feature that git-as-svn currently lacks. We have an issue #126 to track this, however there are no plans to implement it in nearest future.

I think this issue can be closed.
