### ISSUE TITLE
The repository is not signed

### ISSUE THREAD

**Issue by PavelPavlenko95** [bozaro/git-as-svn#422]
Hey, i've got this error during git-as-svn installation process. I tried some solutions from here https://askubuntu.com/questions/732985/force-update-from-unsigned-repository but it didn't help. 
![repo_not_signed](https://user-images.githubusercontent.com/58745190/120987618-6e007180-c786-11eb-876d-73a3ee93a005.png)

**Comment by slonopotamus** [comment]
Please, see #370. Repository on Bintray is dead. For now, you can directly install .deb files from [GitHub Releases](https://github.com/bozaro/git-as-svn/releases).

**Comment by Alexandre-Silva** [comment]
Hello, 

I just want to let you know that the documentation still instructs the usage of Bintray.

https://bozaro.github.io/git-as-svn/htmlsingle/git-as-svn.html#_installation_on_debianubuntu

**Comment by slonopotamus** [comment]
I know. This is supposed to be fixed by #370.

**Comment by Alexandre-Silva** [comment]
Hmm, I see. But wouldn't it be a good idea no mention in the documentation that the debian/ubunto repository is (at least temporarily) not working? I'm asking because I spent some time trying to make work before landing on this issue and I may not be the only one.

BTW, thanks for this tool. It's exactly what I needed.

**Comment by slonopotamus** [comment]
Starting with git-as-svn 2.0.0, debian packages are now published to [cloudsmith.io](https://cloudsmith.io/~git-as-svn/repos/git-as-svn/packages/).
