### ISSUE TITLE
Add support for svn layout for multiple branches

### ISSUE THREAD

**Issue by bozaro** [bozaro/git-as-svn#69]

**Comment by thefallentree** [comment]
any update on this?

**Comment by bozaro** [comment]
Nope. No updates yet.
This task is still planned, but current main goal is "simple deployment and GitLab integration".
As workaround you can work add create many svn-repositories for one git-repositry (one repo per branch).

**Comment by bmaehr** [comment]
The project seams very interesting for me (as a developer) because in IMHO git is much to complex because of the local repository. But the lack of supporting branches in this project is to bad. Can you perhaps explain why it is not implemented? Is it to difficult to map the Git branches to SVN branches and vice versa?

**Comment by slonopotamus** [comment]
It is not implemented (yet) because initially nothing is implemented in any software until someone implements it.

This task is not trivial if done properly. We need to provide linear revision numbering to svn users *across* all branches. This becomes even more complicated because branches can be creeated and deleted in git. Normally, git just forgets about deleted branch. But if we implement /branches or /tags directory, we cannot simply forget about deleted branches because we need to show svn users that in revision N that branch was deleted. If we don't do that, svn client that checked out /branches won't work properly.

It is much simpler to expose git branches as unrelated svn repositories via git-as-svn (and you already can do this manually via git-as-svn.conf), but nobody implemented automatic branch discovery (yet).

**Comment by slonopotamus** [comment]
I believe, what we currently have is Good Enough, especially with #272 and #248. We still don't have `/branches`, so user cannot list branches via svn, but supporting that is too complex and not worth it.
